capdebuginfo: reduced input arguments from 2 to 1
Signed-off-by: Aleem Arshad <arshad_aleem@mentor.com>

diff --git a/scripts/capdebuginfo b/scripts/capdebuginfo
--- a/scripts/capdebuginfo
+++ b/scripts/capdebuginfo
@@ -12,7 +12,6 @@
 # version 2.  This program  is licensed "as is" without any warranty of any
 # kind, whether express or implied.
 
-
 # Variables
 unset BUILDERR   # Path and filename of the MEL build error log file
 unset MELDIR     # Root path of the MEL installation directory
@@ -51,7 +50,13 @@ END
 abspath () {
     readlink -e "${1}"
 }
-
+setup_environment() {
+if("Ubuntu"=`lsb_release -i -s`) then
+   source "${MELDIR}"/meta-mentor/scripts/setup-ubuntu
+else
+   source "${MELDIR}"/meta-mentor/scripts/setup-rh
+fi
+}
 
 # Process input arguments to the script
 #   Input:  $@
@@ -60,19 +65,19 @@ process_cmdline_args () {
       case "${opt}" in
          e)
             # Handle getops with invalid input
-            if [[ ${OPTARG} == -* ]] ; then
-               echo "Invalid input for option -${opt}"
+            if [[ "${OPTARG}" == -* ]] ; then
+               echo "Invalid input for option -"${opt}""
                shift $((OPTIND-1))
                break
             else
-               BUILDERR=$(find ${BUILDDIR}/tmp/work/ -maxdepth 2 -type d -name "${OPTARG}")
+               BUILDERR=$(find "${BUILDDIR}/tmp/work/" -maxdepth 2 -type d -name "${OPTARG}")
             fi
             ;;
          :)
-            echo "Option -${OPTARG} requires an argument." >&2
+            echo "Option -"${OPTARG}" requires an argument." >&2
             ;;
          \?)
-            echo "Invalid option: -${OPTARG}" >&2
+            echo "Invalid option: -"${OPTARG}"" >&2
             ;;
          h)
             usage
@@ -90,16 +95,16 @@ get_hostinfo () {
    local __output="${1}/host/${2}"
    
    echo -en "\nHost Distro Info:\n" >> ${__output}
-   lsb_release -a >> ${__output} 2> /dev/null
-   echo -en "\nHost System Info:\n" >> ${__output}
-   uname -a >> ${__output}
-   echo -en "\nHost env Info:\n" >> ${__output}
-   printenv | sort >> ${__output}
-   echo -en "\nHost disk space usage:\n" >> ${__output}
-   df -h >> ${__output}
-   echo -en "\nHost memory usage:\n" >> ${__output}
-   free -ht >> ${__output}
-   echo -en "\n" >> ${__output}
+   lsb_release -a >> "${__output}" 2> /dev/null
+   echo -en "\nHost System Info:\n" >> "${__output}"
+   uname -a >> "${__output}"
+   echo -en "\nHost env Info:\n" >> "${__output}"
+   printenv | sort >> "${__output}"
+   echo -en "\nHost disk space usage:\n" >> "${__output}"
+   df -h >> "${__output}"
+   echo -en "\nHost memory usage:\n" >> "${__output}"
+   free -ht >> "${__output}"
+   echo -en "\n" >> "${__output}"
 }
 
 
@@ -116,23 +121,23 @@ get_hostlicenseinfo () {
    echo -en "\n${__licensename}:\n" >> ${__output}
    # Check if license variable is set in shell environment
    if [ -n "${__license}" ]; then
-      echo -en "${__license}\n" >> ${__output}
+      echo -en "${__license}\n" >> "${__output}"
       # Process license variable string
       for i in $(echo "${__license//:/$'\n'}"); do
          # Check if entry is a license file and exists
          if [ -f "${i}" ]; then
             # Make a copy of the license file
-            cp ${i} ${__outputdir}/host/.
+            cp "${i}" "${__outputdir}/host/."
          # Check if entry is a license server
-         elif [[ ${i} == *"@"* ]]; then
+         elif [[ "${i}" == *"@"* ]]; then
             echo -en "\n${i} is a license server\n" >> ${__output}
          # Entry is invalid
          else
-            echo -en "\n${i} does not seem to be a valid entry\n" >> ${__output}
+            echo -en "\n${i} does not seem to be a valid entry\n" >> "${__output}"
          fi
       done
    else
-      echo -en "\n${__licensename} is not set!\n" >> ${__output}
+      echo -en "\n${__licensename} is not set!\n" >> "${__output}"
    fi
 }
 
@@ -150,17 +155,13 @@ get_hostprereqsinfo () {
    echo -en "\nHost OS is ${__hostos_distid} ${__hostos_distvers}:\n" >> ${__output}
    case "${__hostos_distid}" in
       Ubuntu)
-         __pkgs="bmap-tools bzip2 chrpath cvs diffstat gawk gcc git-core gzip g++ \
-                 libgl1-mesa-dev libglu1-mesa-dev libncurses5-dev libsdl1.2-dev \
-                 lsb-release make patch python python3 subversion tar texinfo \
-                 texi2html ubuntu-minimal ubuntu-standard zip"
+	 source "${MELDIR}"/meta-mentor/scripts/setup-ubuntu
+         __pkgs="$PKGS"
          dpkg-query -W -f='${binary:Package} ${Version} ${db:Status-Status}\n' ${__pkgs} >> ${__output}
          ;;      
       CentOS|RedHat*)
-         __pkgs="bzip2 chrpath cvs diffstat gawk gcc gcc-c++ git glibc-devel \ 
-                 glibc-static gzip make ncurses-devel patch perl-Thread-Queue \
-                 python python34 python-virtualenv redhat-lsb SDL-devel sqlite \
-                 subversion tar tetex texinfo texi2html wget"
+         source "${MELDIR}"/meta-mentor/scripts/setup-rh
+         __pkgs="$packages"
          rpm -q ${__pkgs} >> ${__output}
          ;;
    esac
